In [17]:
# 1. Establish a connection between Python and the Sakila database.


import pandas as pd
from sqlalchemy import create_engine
import getpass
from sqlalchemy import text

password = getpass.getpass("Enter password: ")

sk = "sakila"

connection_string = f"mysql+pymysql://root:{password}@localhost/{sk}"

engine = create_engine(connection_string)

Enter password:  ········

In [22]:
# 2. Write a Python function called rentals_month that retrieves rental data for a given month and year (passed as parameters) 
#    from the Sakila database as a Pandas DataFrame. The function should take in three parameters:

# engine: an object representing the database connection engine to be used to establish a connection to the Sakila database.
# month: an integer representing the month for which rental data is to be retrieved.
# year: an integer representing the year for which rental data is to be retrieved.


def rentals_month(engine, month, year):
    query = f"""
    SELECT *
    FROM rental
    WHERE MONTH(rental_date) = {month}
      AND YEAR(rental_date) = {year};
    """
    
    df = pd.read_sql(query, engine)
    
    return df

In [49]:
df1=rentals_month(engine, 5, 2005)
df1

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53
...,...,...,...,...,...,...,...
1151,1153,2005-05-31 21:36:44,2725,506,2005-06-10 01:26:44,2,2006-02-15 21:30:53
1152,1154,2005-05-31 21:42:09,2732,59,2005-06-08 16:40:09,1,2006-02-15 21:30:53
1153,1155,2005-05-31 22:17:11,2048,251,2005-06-04 20:27:11,2,2006-02-15 21:30:53
1154,1156,2005-05-31 22:37:34,460,106,2005-06-01 23:02:34,2,2006-02-15 21:30:53
1155,1157,2005-05-31 22:47:45,1449,61,2005-06-02 18:01:45,1,2006-02-15 21:30:53

In [46]:
# Develop a Python function called rental_count_month that takes the DataFrame provided by rentals_month as input 
# along with the month and year and returns a new DataFrame containing the number of rentals made by each 
# customer_id during the selected month and year.

# The function should also include the month and year as parameters 
# and use them to name the new column according to the month and year, 
# for example, if the input month is 05 and the year is 2005, the column name should be "rentals_05_2005".

def rental_count_month(df1, month, year):
    column_name = f"rentals_{month}_{year}"

    result = (
        df1.groupby("customer_id")["rental_date"].count().reset_index(name=column_name))
    return result

In [70]:
df2=rental_count_month(df1, 5, 2005)
df2

     customer_id  rentals_5_2005
0              1               2
1              2               1
2              3               2
3              5               3
4              6               3
..           ...             ...
515          594               4
516          595               1
517          596               6
518          597               2
519          599               1

[520 rows x 2 columns]

In [71]:
df3=rental_count_month(df1, 7, 2005)
df3

     customer_id  rentals_7_2005
0              1               2
1              2               1
2              3               2
3              5               3
4              6               3
..           ...             ...
515          594               4
516          595               1
517          596               6
518          597               2
519          599               1

[520 rows x 2 columns]

In [72]:
# 4. Create a Python function called compare_rentals that takes two DataFrames as input 
#    containing the number of rentals made by each customer in different months and years. 
#    The function should return a combined DataFrame with a new 'difference' column, 
#    which is the difference between the number of rentals in the two months.


def compare_rentals(df2, df3):
    
    combined_df = pd.merge(df2, df3, on="customer_id", how="outer")
    
    col1 = combined_df.columns[1]
    col2 = combined_df.columns[2]
    
    combined_df["difference"] = combined_df[col2] - combined_df[col1]
    
    return combined_df

In [77]:
compare_rentals(df2, df3)

     customer_id  rentals_5_2005  rentals_7_2005  difference
0              1               2               2           0
1              2               1               1           0
2              3               2               2           0
3              5               3               3           0
4              6               3               3           0
..           ...             ...             ...         ...
515          594               4               4           0
516          595               1               1           0
517          596               6               6           0
518          597               2               2           0
519          599               1               1           0

[520 rows x 4 columns]